{% set version = "1.3.6" %}

package:
  name: bottleneck
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/B/Bottleneck/Bottleneck-{{ version }}.tar.gz
  sha256: bc15e2545d4282d6f2529597df1bd6e4c5f0c44296b3f8425bc835305bd943c9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - numpy  # [build_platform != target_platform]
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pytest
  imports:
    - bottleneck
    - bottleneck.slow
    - bottleneck.tests
    - bottleneck.reduce
    - bottleneck.nonreduce
    - bottleneck.nonreduce_axis
    - bottleneck.move
  commands:
    - python -c "import bottleneck; bottleneck.test()"

about:
  home: https://github.com/pydata/bottleneck
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Fast NumPy array functions written in Cython.
  description: |
    Bottleneck is a collection of fast NumPy array functions written in
    Cython.
  doc_url: https://bottleneck.readthedocs.io
  dev_url: https://github.com/pydata/bottleneck

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - wesm
    - ocefpaf
    - qwhelan
