{% set name = "Bottleneck" %}
{% set version = "1.2.1" %}
{% set sha256 = "6efcde5f830aed64feafca0359b51db0e184c72af8ba6675b4a99f263922eb36" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - numpy        # [not (win and (py35 or py36))]
    - numpy        # [win and py35]
    - numpy         # [win and py36]
  run:
    - python
    - {{ pin_compatible('numpy') }}   # [not (win and (py35 or py36))]
    - {{ pin_compatible('numpy') }}   # [win and py35]
    - {{ pin_compatible('numpy') }}   # [win and py36]

test:
  requires:
    - nose
  imports:
    - bottleneck
    - bottleneck.slow
    - bottleneck.tests
    - bottleneck.reduce
    - bottleneck.nonreduce
    - bottleneck.nonreduce_axis
    - bottleneck.move
  commands:
    - python -c "import bottleneck; bottleneck.test()"
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://berkeleyanalytics.com/bottleneck
  license: BSD 2-Clause
  license_family: BSD
  license_file: bottleneck/LICENSE
  summary: Fast NumPy array functions written in Cython.
  description: |
    Bottleneck is a collection of fast NumPy array functions written in
    Cython.
  doc_url: http://berkeleyanalytics.com/bottleneck
  dev_url: https://github.com/kwgoodman/bottleneck

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - wesm
    - ocefpaf
