{% set version = "1.4.1" %}

package:
  name: bottleneck
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/B/Bottleneck/bottleneck-{{ version }}.tar.gz
  sha256: 58c66619db62291c9ca3b497b05f40f7b1ff9ac010b88bff1925f3101dae2c89

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - numpy
  run:
    - numpy
    - python

test:
  requires:
    - pytest
    - pip
  imports:
    - bottleneck
    - bottleneck.slow
    - bottleneck.tests
    - bottleneck.reduce
    - bottleneck.nonreduce
    - bottleneck.nonreduce_axis
    - bottleneck.move
  commands:
    - pip check
    - python -c "import bottleneck; bottleneck.test()"

about:
  home: https://github.com/pydata/bottleneck
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Fast NumPy array functions written in Cython.
  description: |
    Bottleneck is a collection of fast NumPy array functions written in
    Cython.
  doc_url: https://bottleneck.readthedocs.io
  dev_url: https://github.com/pydata/bottleneck

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - wesm
    - ocefpaf
    - qwhelan
