{% set version = "1.5.0" %}

package:
  name: bottleneck
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/B/Bottleneck/bottleneck-{{ version }}.tar.gz
  sha256: c860242cf20e69d5aab2ec3c5d6c8c2a15f19e4b25b28b8fca2c2a12cefae9d8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy >=2,<2.3                         # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - versioneer
    - numpy >=2,<2.3
  run:
    - numpy
    - python

test:
  requires:
    - pytest
    - pip
  imports:
    - bottleneck
    - bottleneck.slow
    - bottleneck.tests
    - bottleneck.reduce
    - bottleneck.nonreduce
    - bottleneck.nonreduce_axis
    - bottleneck.move
  commands:
    - pip check
    - python -c "import bottleneck; bottleneck.test()"

about:
  home: https://github.com/pydata/bottleneck
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Fast NumPy array functions written in Cython.
  description: |
    Bottleneck is a collection of fast NumPy array functions written in
    Cython.
  doc_url: https://bottleneck.readthedocs.io
  dev_url: https://github.com/pydata/bottleneck

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - wesm
    - ocefpaf
    - qwhelan
